-- ---------------------------------------------------------------------------
-- V1 — Schéma initial. Fait foi avec docs/diagrammes/D2_modele_donnees.md.
--
-- SQL volontairement portable PostgreSQL / H2 :
--   - pas de type ENUM natif, des VARCHAR + CHECK (les tests tournent sur H2) ;
--   - BIGINT GENERATED BY DEFAULT AS IDENTITY, supporté par les deux ;
--   - TIMESTAMP, l'application écrit et lit en UTC (hibernate.jdbc.time_zone).
-- ---------------------------------------------------------------------------

CREATE TABLE promotion (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE utilisateur (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom          VARCHAR(120) NOT NULL,
    role         VARCHAR(20)  NOT NULL,
    promotion_id BIGINT,
    CONSTRAINT ck_utilisateur_role CHECK (role IN ('FORMATEUR', 'ETUDIANT')),
    CONSTRAINT fk_utilisateur_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id)
);

CREATE INDEX ix_utilisateur_promotion ON utilisateur (promotion_id);

-- RG2  : expiration_at = ouverture_at + 15 minutes, posée par le service.
-- RG20 : cloture_at non nulle = session clôturée, irréversible.
-- RG21 : le code n'est pas devinable. L'unicité est ici posée globalement et
--        non « parmi les sessions actives » comme l'énonce D2 : un index
--        partiel n'est pas portable sur H2, et une unicité globale est une
--        contrainte plus forte, donc toujours suffisante pour RG21.
CREATE TABLE session (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre         VARCHAR(200) NOT NULL,
    code          VARCHAR(6)   NOT NULL UNIQUE,
    ouverture_at  TIMESTAMP    NOT NULL,
    expiration_at TIMESTAMP    NOT NULL,
    cloture_at    TIMESTAMP,
    promotion_id  BIGINT       NOT NULL,
    formateur_id  BIGINT,
    CONSTRAINT ck_session_titre_non_vide CHECK (LENGTH(TRIM(titre)) > 0),
    CONSTRAINT ck_session_expiration_apres_ouverture CHECK (expiration_at > ouverture_at),
    CONSTRAINT fk_session_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id),
    CONSTRAINT fk_session_formateur FOREIGN KEY (formateur_id) REFERENCES utilisateur (id)
);

CREATE INDEX ix_session_promotion ON session (promotion_id);

-- RG14 : toute présence porte sa source.
-- RG15 : au plus une présence par couple (session, étudiant) -> 409 DEJA_PRESENT.
CREATE TABLE presence (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT      NOT NULL,
    etudiant_id BIGINT      NOT NULL,
    source      VARCHAR(20) NOT NULL,
    marquee_at  TIMESTAMP   NOT NULL,
    CONSTRAINT ck_presence_source CHECK (source IN ('ETUDIANT', 'FORMATEUR')),
    CONSTRAINT uk_presence_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT fk_presence_session FOREIGN KEY (session_id) REFERENCES session (id),
    CONSTRAINT fk_presence_etudiant FOREIGN KEY (etudiant_id) REFERENCES utilisateur (id)
);

-- RG16 : au plus un exercice par couple (session, étudiant) -> 409 EXERCICE_DEJA_DEPOSE.
-- RG18 : le lien est une URL absolue http(s) d'au plus 2048 caractères.
CREATE TABLE exercice (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT        NOT NULL,
    etudiant_id BIGINT        NOT NULL,
    lien        VARCHAR(2048) NOT NULL,
    statut      VARCHAR(20)   NOT NULL,
    depose_at   TIMESTAMP     NOT NULL,
    CONSTRAINT ck_exercice_statut CHECK (statut IN ('DEPOSE', 'EN_ATTENTE', 'RELU')),
    CONSTRAINT uk_exercice_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT fk_exercice_session FOREIGN KEY (session_id) REFERENCES session (id),
    CONSTRAINT fk_exercice_etudiant FOREIGN KEY (etudiant_id) REFERENCES utilisateur (id)
);

-- RG6 : exactement un relecteur par exercice -> UNIQUE (exercice_id).
-- RG9 : la note est un entier de 0 à 20 -> 400 NOTE_INVALIDE.
-- RG11 : statut ASSIGNEE tant que la relecture n'est pas rendue.
-- RG5 (relecteur != auteur) est vérifié en service : le SQL ne peut pas
--      porter une contrainte entre deux tables.
CREATE TABLE relecture (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id  BIGINT      NOT NULL UNIQUE,
    relecteur_id BIGINT      NOT NULL,
    statut       VARCHAR(20) NOT NULL,
    note         INTEGER,
    commentaire  VARCHAR(2000),
    assignee_at  TIMESTAMP   NOT NULL,
    rendue_at    TIMESTAMP,
    CONSTRAINT ck_relecture_statut CHECK (statut IN ('ASSIGNEE', 'RENDUE')),
    CONSTRAINT ck_relecture_note CHECK (note IS NULL OR (note BETWEEN 0 AND 20)),
    CONSTRAINT fk_relecture_exercice FOREIGN KEY (exercice_id) REFERENCES exercice (id),
    CONSTRAINT fk_relecture_relecteur FOREIGN KEY (relecteur_id) REFERENCES utilisateur (id)
);

CREATE INDEX ix_relecture_relecteur ON relecture (relecteur_id);

-- RG4 : 5 échecs consécutifs -> 2 minutes de blocage. Persisté, et non gardé
--       en mémoire : sinon la règle se contourne en redémarrant le serveur.
CREATE TABLE tentative_code (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etudiant_id         BIGINT  NOT NULL UNIQUE,
    echecs_consecutifs  INTEGER NOT NULL DEFAULT 0,
    bloque_jusqua       TIMESTAMP,
    CONSTRAINT fk_tentative_etudiant FOREIGN KEY (etudiant_id) REFERENCES utilisateur (id)
);
